// Auto-generated by OmniCrawl AppCaptureManager.
// Replace this placeholder with site- or app-specific hooks as needed.

setImmediate(function () {
  console.log('[omnicrawl] frida helper loaded for target.bundle.id');

  if (typeof Java !== 'undefined' && Java.available) {
    Java.perform(function () {
      console.log('[omnicrawl] Java runtime available; install SSL pinning or JS bridge hooks here.');
    });
    return;
  }

  console.log('[omnicrawl] Java runtime unavailable; attach native hooks manually if required.');
});

rpc.exports = {
  ping() {
    return 'pong';
  },
};
