// Auto-generated by OmniCrawl AppCaptureManager.
// Generic fallback template. Replace with platform-specific hooks as needed.

setImmediate(function () {
  console.log('[omnicrawl] generic frida helper loaded for target.bundle.id');

  if (typeof Java !== 'undefined' && Java.available) {
    Java.perform(function () {
      console.log('[omnicrawl] Java runtime available; consider swapping in the Android template.');
    });
    return;
  }

  if (typeof ObjC !== 'undefined' && ObjC.available) {
    console.log('[omnicrawl] Objective-C runtime available; consider swapping in the iOS template.');
    return;
  }

  console.log('[omnicrawl] no managed runtime detected; attach native hooks manually if required.');
});

rpc.exports = {
  ping() {
    return 'pong';
  },
};
